ingress:
  enabled: true
  ingressClassName: nginx
  path: /
  pathType: Prefix
  hosts:
    - grafana.172.19.0.1.sslip.io
persistence:
  type: pvc
  enabled: true
  torageClassName: standard
  accessModes:
    - ReadWriteOnce
  size: 10Gi
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-operated:9090
        basicAuth: false
        isDefault: false
        version: 1
        orgId: 1
        editable: false
      - name: Tempo
        type: tempo
        access: proxy
        orgId: 1
        url: http://tempo:3100
        basicAuth: false
        isDefault: false
        version: 1
        editable: false
        apiVersion: 1
        uid: tempo
      - name: Loki
        type: loki
        uid: loki
        access: proxy
        orgId: 1
        url: http://loki-gateway
        basicAuth: false
        isDefault: false
        version: 1
        editable: true
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: false
        options:
          path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    SpringBoot-APM-Dashboard:
      gnetId: 12900
      revision: 3
      datasource: Prometheus
env:
  GF_AUTH_ANONYMOUS_ENABLED: true
  GF_AUTH_ANONYMOUS_ORG_ROLE: 'Admin'
  GF_AUTH_DISABLE_LOGIN_FORM: true
  GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/default/SpringBoot-APM-Dashboard.json
