stages:
  - pre_build
  - build

workflow:
  rules:
    - if: $CI_COMMIT_TAG =~ '/^v\d+\.\d+\.\d+$/' || $CI_COMMIT_BRANCH == 'main'
      changes:
        - .gitlab-ci.yml

cache_test:
  stage: pre_build
  image:
    name: docker:24-dind
    entrypoint: ["/bin/ash", "-c"]
  script:
    - |
      mkdir -p node_modules
      ls -lh node_modules/
      echo test > node_modules/package.json
  cache:
    key: $CI_PROJECT_NAME-cache
    paths:
      - node_modules/
    policy: pull-push

dind:
  stage: build
  image:
    name: docker:24-dind
    entrypoint: ["/bin/ash", "-c"]
  before_script:
    - sed -i '/# Mount \/tmp/,+3d' /usr/local/bin/dind
    - sed -i '/:2375/,1d' /usr/local/bin/dockerd-entrypoint.sh
    - export TINI_SUBREAPER=
    - export DOCKER_TLS_CERTDIR=
    - export DOCKER_TLS_VERIFY=
    - export DOCKER_HOST=unix:///var/run/docker.sock
    - nohup dockerd-entrypoint.sh --insecure-registry=registry.172.19.255.201.sslip.io &
    - |
      echo "[$(date)] Wait Docker startup"
      tries=0
      d_timeout=60
      until docker info >/dev/null 2>&1; do
        if [ "$tries" -gt "$d_timeout" ]; then
          echo "[$(date)] Timed out trying to connect to docker" >&2;
          exit 1;
        fi
        tries=$(( $tries + 1 ));
        sleep 1;
      done
    - echo "[$(date)] Docker started"
  script:
    - apk add --no-cache --update git skopeo
    - docker info
    - echo "$CI_REGISTRY_PASSWORD" | docker login http://$CI_REGISTRY -u "$CI_REGISTRY_USER" --password-stdin
    - IMAGE_TAG="${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}"
    - docker pull alpine:3.18
    - docker tag alpine:3.18 $CI_REGISTRY_IMAGE:$IMAGE_TAG
    # - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG . --progress=plain
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
    - echo "$CI_REGISTRY_PASSWORD" | skopeo login --tls-verify=false http://$CI_REGISTRY -u "$CI_REGISTRY_USER" --password-stdin
    - skopeo copy --src-tls-verify=false --dest-tls-verify=false docker://docker.io/library/alpine:3.17 docker://$CI_REGISTRY_IMAGE:3.17
    - |
      ls -lh node_modules/
      echo test > node_modules/package.lock
  cache:
    key: $CI_PROJECT_NAME-cache
    paths:
      - node_modules/
    policy: pull