apiVersion: v1
kind: Service
metadata:
  name: dind
spec:
  ports:
  - name: docker
    port: 2375
    protocol: TCP
    targetPort: 2375
  selector:
    app: dind
    name: dind
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 300
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dind
  template:
    metadata:
      labels:
        name: dind
        app: dind
    spec:
      containers:
        - image: docker:24-dind
          args:
            - --insecure-registry=registry.172.19.255.201.sslip.io
          # imagePullPolicy: Always
          name: dind
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          ports:
            - containerPort: 2375
          securityContext:
            privileged: true
      restartPolicy: Always