apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- statefulset.yaml
- service.yaml
secretGenerator:
- name: dind-client
  files:
  - certs/client/ca.pem
  - certs/client/cert.pem
  - certs/client/key.pem
- name: dind-server
  files:
  - certs/server/ca.pem
  - certs/server/cert.pem
  - certs/server/key.pem
generatorOptions:
  disableNameSuffixHash: true