apiVersion: v1
kind: Service
metadata:
  name: docker
spec:
  ports:
  - name: docker
    port: 2376
    protocol: TCP
    targetPort: 2376
  selector:
    app: dind
    name: dind
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 300
  type: ClusterIP